# Use multi-stage builds to optimize the final image size and security
# ----------------------------------------------------------- Stage 1: Create base image, use alpine for smaller size
FROM golang:1.20-alpine AS base
# Install Git and certs for module downloads and HTTPS
RUN apk add --no-cache git ca-certificates
# Working directory for the application
WORKDIR /app
# Copy go.mod and go.sum first, because they are less likely to change and will allow us to cache the dependencies
COPY go.mod go.sum ./
# Cache Go modules to speed up builds
# target1 is the cache directory for Go modules, target2 is the cache directory for Go build
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download



# ----------------------------------------------------------- Stage 2: Development stage
# This stage is used for development purposes only
# To use this stage, run the following command: docker build --target dev -t api-go-dev && docker run -it --rm api-go-dev
FROM base AS dev
# Install Air for hot reload and Delve for debugging
RUN go install github.com/cosmtrek/air@v1.40.4 && \
    go install github.com/go-delve/delve/cmd/dlv@v1.9.1
# Copy air, delve, and other necessary files into the container
COPY . .
# use air for hot reload command
CMD ["air", "-c", ".air.toml"]



# ----------------------------------------------------------- Stage 3: Build stage
# This stage is used to build the application and healthcheck binary
FROM base AS build
# Create a non-root user
RUN adduser -D -u 1001 nonroot
# Copy the application files into the container
COPY . .
# Build healthcheck binary
RUN go build -ldflags="-linkmode external -extldflags -static -s -w" -tags netgo -o healthcheck ./healthcheck/healthcheck.go
# Build application binary
RUN go build -ldflags="-linkmode external -extldflags -static -s -w" -tags netgo -o api-golang



# ----------------------------------------------------------- Stage 4: Production stage
# To use this stage, run the following command: docker build -t api-go-prod && docker run -it --rm api-go-prod
# This stage is used for the final production image
# Use scratch as the base image for a minimal image size and better security
FROM scratch
# ENV GIN_MODE=release, which is used to set the Gin framework to release mode
# This is important for performance and security in production
ENV GIN_MODE=release
# Working directory for the application
WORKDIR /
# Copy non-root user
COPY --from=build /etc/passwd /etc/passwd
# Copy built binaries
COPY --from=build /app/healthcheck healthcheck
COPY --from=build /app/api-golang api-golang
# Add non-root user to the image, this is important for security reasons
USER nonroot
# Expose the port that the application will run on 8080
EXPOSE 8080
# CMD /api-golang to run the application when the container starts
CMD ["/api-golang"]