# Dockerfile for React Client

FROM node:18-alpine

# Set the working directory
WORKDIR /app

COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

EXPOSE 1516

# Start the app
CMD ["npm", "run", "dev"]