version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: docker_db
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_pass
    ports:
      - "5432:5432"
  
  app:
    build: . # .(dot) indicates the execution of the dockerfile exists in the current directory
    depends_on:
      - db