# Use multi-stage builds to optimize the final image size and security
# ----------------------------------------------------------- Stage 1: Create base image, use alpine for smaller size
FROM node:18-alpine AS base
# Set the working directory
WORKDIR /app
COPY package.json package-lock.json ./
# Install dependencies using mount cache for faster builds
RUN --mount=type=cache,target=/app/.npm \
    npm set cache /app/.npm && \
    npm install

COPY . .


# ----------------------------------------------------------- Stage 2: development stage
# This stage is used for development purposes only
FROM base AS dev
# Expose the react app port (1516)
EXPOSE 1516
# Build the production-ready static files
CMD ["npm", "run", "dev"]