services:
  api-golang:
    build:
      context: ./api-golang
      target: dev
    ports:
      - "8080:8080"
    env_file:
      - ./api-golang/.env
    networks:
      - MSSmall_app
    depends_on:
      - postgres

  api-node:
    build:
      context: ./api-node
      target: dev
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - MSSmall_app
    env_file:
      - ./api-node/.env
    depends_on:
      - postgres

  api-react:
    build:
      context: ./client-react
      target: dev
      dockerfile: dockerfile.dev
    ports:
      - "1515:1516"
    networks:
      - MSSmall_app
    depends_on:
      - api-node
      - api-golang