version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: docker_db
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: