# Use multi-stage builds to optimize the final image size and security
# ----------------------------------------------------------- Stage 1: Create base image, use alpine for smaller size
FROM node:23-alpine AS base
WORKDIR /usr/src/app
# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm install
# Copy the rest of the code
COPY . .


# ----------------------------------------------------------- Stage 2: Development stage
# This stage is used for development purposes only
FROM base AS dev
# Expose the Node app port (3000)
EXPOSE 3000
# Start the application
CMD ["npm", "run", "dev"]